# Generated by Django 5.1.7 on 2025-03-14 20:24

import django.utils.timezone
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clinic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(validators=[utils.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(upload_to='clinic_images', validators=[utils.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone]),
        ),
    ]
